### ISSUE TITLE
maven-central release missing

### ISSUE THREAD

**Issue by cleiner** [dropwizard/dropwizard-jdbi#1]
The jdbi2 module is not available on Maven Central -- this is also indicated by the badge in the readme:
![grafik](https://user-images.githubusercontent.com/13875643/72889233-7d0c8e00-3d0f-11ea-9ffd-f253ad21a238.png)

Is there anything preventing it from being released?

**Comment by joschi** [comment]
@cleiner Thanks for the reminder. The main reasons for the missing release(s) were lack of time and lack of requests to publish them. 😉

dropwizard-jdbi 2.0.0 and 2.0.1 have been released and should appear on Maven Central within the next few hours.

https://github.com/dropwizard/dropwizard-jdbi/releases/tag/v2.0.0
https://github.com/dropwizard/dropwizard-jdbi/releases/tag/v2.0.1
